[package]
name = "what-to-do"
version = "0.1.0"
authors = ["Kaleblub <kaleblub.pythonanywhere.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2" }